version: 0.2
phases:
  install:
    commands:
      - echo install started `date`
      # - npm ci
  pre_build:
    commands:
      - echo pre_build started `date`
      # - echo $CODEBUILD_SRC_DIR
      # - echo cd ${CODEBUILD_SRC_DIR} && ls -a
      # - echo $CODEBUILD_SOURCE_VERSION
      # - echo $CODEBUILD_SOURCE_REPO_URL
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - echo $CODEBUILD_WEBHOOK_TRIGGER
  build:
    commands:
      - echo build started `date`
      - mkdir fe_build
      - cd fe_build && touch fe_build.txt