version: 0.2
phases:
  install:
    commands:
      - echo install started `date`
      # - npm ci
  pre_build:
    commands:
      - echo pre_build started `date`
      - GIT_HASH_TO_BUILD=`cat git-commit-hash`
      - echo Commit hash is $GIT_HASH
      - GIT_BRANCH=`cat git-branch`
      - echo Commit Branch is $GIT_BRANCH
      # - echo $CODEBUILD_SRC_DIR
      # - echo $CODEBUILD_SOURCE_VERSION
      # - echo $CODEBUILD_SOURCE_REPO_URL
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - echo $CODEBUILD_WEBHOOK_TRIGGER
  build:
    commands:
      - echo build started `date`
      - mkdir fe_build
      - cd fe_build && touch fe_build.txt && zip -rq fe_build * .

artifacts:
  files:
    - 'fe_build/*'
  name: buildFEOutput
  discard-paths: yes