version: 0.2
phases:
  install:
    commands:
      - echo install started `date`
      # - npm ci
  pre_build:
    commands:
      - echo pre_build started `date`
      # - echo $CODEBUILD_SRC_DIR
      # - echo $CODEBUILD_SOURCE_VERSION
      # - echo $CODEBUILD_SOURCE_REPO_URL
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - echo $CODEBUILD_WEBHOOK_TRIGGER
  build:
    commands:
      - echo build started `date`
      - mkdir be_build
      - cd be_build && touch be_build.txt && zip -rq be_build * .

artifacts:
  files:
    - 'be_build/*'
  name: buildBEOutput
  discard-paths: yes