version: 0.2

env:
  variables:
    GIT_REPO_URL: 'github.com/ivacko/ci-cd-test.git'
  parameter-store:
    GIT_OAUTH_TOKEN: '/git/oauth/token'

phases:
  pre_build:
    commands:
      - echo pre_build started `date`
      - GIT_HASH_TO_BUILD=`cat git-commit-hash`
      - echo Commit hash is:$GIT_HASH
      - GIT_BRANCH=`cat git-branch`
      - echo Commit Branch is $GIT_BRANCH
      - cd $CODEBUILD_SRC_DIR_buildFEOutput && ls -a
      - cd $CODEBUILD_SRC_DIR_buildBEOutput && ls -a
      - cd $CODEBUILD_SRC_DIR && ls -a
      # - echo $CODEBUILD_SOURCE_VERSION
      # - echo $CODEBUILD_SOURCE_REPO_URL
      # - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      # - echo $CODEBUILD_WEBHOOK_TRIGGER
  build:
    commands:
      - echo build started `date`
      - echo upload artifact to S3
      - echo create application version on EB
      - echo update EB env to deploy new version
      - LATEST_GIT_HASH=`git ls-remote https://$GIT_OAUTH_TOKEN@$GIT_REPO_URL refs/heads/$GIT_BRANCH | cut -f 1`
      - echo $LATEST_GIT_HASH
      - echo $GIT_HASH_TO_BUILD
      - |
        if [ "$GIT_HASH_TO_BUILD" = "$LATEST_GIT_HASH"] ; then
          echo Deploy App
        else
          echo There is new version that will be deployed soon
        fi