version: 0.2

env:
  parameter-store:
    S3_BUCKET: '/ci-cd/s3bucket'

phases:
  install:
    commands:
      - echo install started `date`
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm ci
  pre_build:
    commands:
      - echo pre_build started `date`
      - GIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $GIT_HASH >> git-commit-hash 2>&1
      - cp -pr git-commit-hash ./front-end
      - npm run test -- --silent
  build:
    commands:
      - echo build started `date`
      - TRIGGER=$(echo $CODEBUILD_SOURCE_VERSION | cut -d/ -f1)
      - |
        if [ "$TRIGGER" != "pr" ] ; then
          if [ ! -z "$CODEBUILD_WEBHOOK_TRIGGER" ] ; then
            BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -d/ -f2)
          fi

          if [ "$BRANCH" != "master" ] && [ "$BRANCH" != "staging_ci" ] && [ "$BRANCH" != "uat" ] ; then
            echo "Selected branch is not supported.
            To start build manually use 'BRANCH' env par.
            Allowed values are master, staging_ci, uat."
            exit 1
          fi

          echo packaging and uploading tested version of the app for build stage
          echo $BRANCH >> git-branch 2>&1

          - |
            if [ "$BRANCH" = "master" ] ; then
              BUILD_ENVIRONMENT=prod
            fi

            if [ "$BRANCH" = "staging_ci" ] ; then
              BUILD_ENVIRONMENT=staging
            fi

            if [ "$BRANCH" = "uat" ] ; then
              BUILD_ENVIRONMENT=uat
            fi

          echo $BUILD_ENVIRONMENT >> build-environment 2>&1

          zip -rq --exclude=*node_modules* $BRANCH * .
          aws s3 cp $BRANCH.zip s3://$S3_BUCKET/$BUILD_ENVIRONMENT-testedVersion/$BRANCH.zip --metadata '{"githash":$GIT_HASH}'
        fi
